"use client";
import { useEffect, useMemo, useRef, useState } from "react";

type MonthPoint={month:string;assets:number;liabilities:number;net:number;categories:Record<string,number>};
type AccountSeries={id:number;name:string;kind:string;category:string;currency:string;points:Array<{month:string;value:number;nativeValue:number}>};
type Analytics={months:MonthPoint[];accounts:AccountSeries[]};
const money=(value:number)=>new Intl.NumberFormat("zh-CN",{maximumFractionDigits:0}).format(value);
const periods:[[number,string],[number,string],[number,string],[number,string]]=[[6,"6月"],[12,"12月"],[24,"24月"],[0,"全部"]];
const palette=["#1f5948","#b16a61","#c09443","#517da2","#8065a4"];
const ACCOUNT_SELECTION_KEY="household-ledger-analysis-accounts";

function RangeButtons({value,onChange}:{value:number;onChange:(value:number)=>void}){return <div className="trend-ranges">{periods.map(([number,text])=><button key={number} className={value===number?"active":""} onClick={()=>onChange(number)}>{text}</button>)}</div>;}
function scale(values:number[],height:number,top:number,bottom:number){const min=Math.min(0,...values),max=Math.max(0,...values),padding=(max-min||1)*.08,lo=min-padding,hi=max+padding,range=hi-lo;return{lo,hi,y:(value:number)=>top+(hi-value)*(height-top-bottom)/range};}
function monthAction(month:string,onSelectMonth:(month:string)=>void){return{role:"button",tabIndex:0,onClick:()=>onSelectMonth(month),onKeyDown:(event:React.KeyboardEvent)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();onSelectMonth(month);}}};}

function TotalsChart({points,onSelectMonth}:{points:MonthPoint[];onSelectMonth:(month:string)=>void}){
  const[hover,setHover]=useState<MonthPoint|null>(null),w=900,h=270,left=74,right=22,top=26,bottom=38;
  const chart=scale(points.flatMap(point=>[point.assets,point.liabilities,point.net]),h,top,bottom),x=(index:number)=>left+index*(w-left-right)/Math.max(1,points.length-1);
  const series=[{key:"assets" as const,label:"总资产",color:"#438065"},{key:"liabilities" as const,label:"总负债",color:"#b16a61"},{key:"net" as const,label:"净资产",color:"#c09443"}];
  return <section className="analytics-card"><div className="analytics-heading"><div><h3>资产、负债与净资产趋势</h3><p>AUD · 点击月份查看当月账户明细</p></div><div className="chart-legend">{series.map(item=><span key={item.key}><i style={{background:item.color}}/>{item.label}</span>)}</div></div>{hover&&<div className="analytics-tooltip"><b>{hover.month}</b><span>资产 ${money(hover.assets)}</span><span>负债 ${money(hover.liabilities)}</span><span>净资产 ${money(hover.net)}</span></div>}<svg viewBox={`0 0 ${w} ${h}`} aria-label="资产、负债与净资产趋势图"><line className="analytics-grid" x1={left} x2={w-right} y1={chart.y(0)} y2={chart.y(0)}/><text className="axis-value" x={left-8} y={top+4} textAnchor="end">${money(chart.hi)}</text><text className="axis-value" x={left-8} y={h-bottom+4} textAnchor="end">${money(chart.lo)}</text>{series.map(item=><path key={item.key} className="analytics-line" stroke={item.color} d={points.map((point,index)=>`${index?"L":"M"}${x(index)},${chart.y(point[item.key])}`).join(" ")}/>) }{points.map((point,index)=><g key={point.month} className="clickable-month" {...monthAction(point.month,onSelectMonth)} onMouseEnter={()=>setHover(point)} onMouseLeave={()=>setHover(null)}><rect x={x(index)-Math.max(8,(w-left-right)/Math.max(1,points.length-1)/2)} y={top} width={Math.max(16,(w-left-right)/Math.max(1,points.length-1))} height={h-top-bottom} fill="transparent"/><text x={x(index)} y={h-8} textAnchor="middle">{point.month.slice(2)}</text>{series.map(item=><circle key={item.key} cx={x(index)} cy={chart.y(point[item.key])} r="4" fill={item.color}/>)}</g>)}</svg></section>;
}

const categoryItems=[{key:"流动资产",color:"#5f9a7e"},{key:"投资资产",color:"#447862"},{key:"自用资产",color:"#b6a36c"},{key:"短期负债",color:"#d3978d"},{key:"长期负债",color:"#a65f58"}];
function CategoryChart({points,onSelectMonth}:{points:MonthPoint[];onSelectMonth:(month:string)=>void}){
  const[hover,setHover]=useState<MonthPoint|null>(null),w=900,h=300,left=55,right=20,top=28,bottom=42,max=Math.max(1,...points.flatMap(point=>[point.assets,point.liabilities])),available=h-top-bottom,group=(w-left-right)/Math.max(1,points.length),bar=Math.min(14,Math.max(5,group*.25));
  return <section className="analytics-card"><div className="analytics-heading"><div><h3>资产负债分类堆叠趋势</h3><p>每月左侧为资产，右侧为负债 · AUD</p></div><div className="chart-legend category-legend">{categoryItems.map(item=><span key={item.key}><i style={{background:item.color}}/>{item.key}</span>)}</div></div>{hover&&<div className="analytics-tooltip"><b>{hover.month}</b>{categoryItems.map(item=><span key={item.key}>{item.key} ${money(hover.categories[item.key]||0)}</span>)}</div>}<svg viewBox={`0 0 ${w} ${h}`} aria-label="资产负债分类堆叠趋势图"><line className="analytics-grid" x1={left} x2={w-right} y1={h-bottom} y2={h-bottom}/>{points.map((point,index)=>{const center=left+group*(index+.5);let assetY=h-bottom,liabilityY=h-bottom;return <g key={point.month} className="clickable-month" {...monthAction(point.month,onSelectMonth)} onMouseEnter={()=>setHover(point)} onMouseLeave={()=>setHover(null)}><rect x={center-group/2} y={top} width={group} height={available} fill="transparent"/>{categoryItems.slice(0,3).map(item=>{const height=(point.categories[item.key]||0)/max*available;assetY-=height;return <rect key={item.key} x={center-bar-2} y={assetY} width={bar} height={height} fill={item.color}><title>{item.key} ${money(point.categories[item.key]||0)}</title></rect>;})}{categoryItems.slice(3).map(item=>{const height=(point.categories[item.key]||0)/max*available;liabilityY-=height;return <rect key={item.key} x={center+2} y={liabilityY} width={bar} height={height} fill={item.color}><title>{item.key} ${money(point.categories[item.key]||0)}</title></rect>;})}<text x={center} y={h-10} textAnchor="middle">{point.month.slice(2)}</text></g>;})}</svg></section>;
}

function AccountChart({accounts,months,onSelectMonth}:{accounts:AccountSeries[];months:MonthPoint[];onSelectMonth:(month:string)=>void}){
  const[selected,setSelected]=useState<number[]>(()=>[...accounts].sort((a,b)=>Math.abs(b.points.at(-1)?.value||0)-Math.abs(a.points.at(-1)?.value||0)).slice(0,3).map(account=>account.id)),[picker,setPicker]=useState(false),[hover,setHover]=useState<{month:string;values:Array<{name:string;value:number}>}|null>(null);
  const preferenceLoaded=useRef(false);
  useEffect(()=>{const timer=window.setTimeout(()=>{try{const stored=JSON.parse(localStorage.getItem(ACCOUNT_SELECTION_KEY)||"[]");const valid=Array.isArray(stored)?stored.map(Number).filter(id=>accounts.some(account=>account.id===id)).slice(0,5):[];preferenceLoaded.current=true;if(valid.length)setSelected(valid);}catch{preferenceLoaded.current=true;}},0);return()=>window.clearTimeout(timer);},[accounts]);
  useEffect(()=>{if(preferenceLoaded.current)localStorage.setItem(ACCOUNT_SELECTION_KEY,JSON.stringify(selected));},[selected]);
  const chosen=accounts.filter(account=>selected.includes(account.id)),w=900,h=290,left=74,right=22,top=28,bottom=38,values=chosen.flatMap(account=>account.points.map(point=>point.value)),chart=scale(values.length?values:[0],h,top,bottom),monthList=months.map(point=>point.month),x=(index:number)=>left+index*(w-left-right)/Math.max(1,monthList.length-1);
  const toggle=(id:number)=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):current.length<5?[...current,id]:current);
  return <section className="analytics-card account-trend-card"><div className="analytics-heading"><div><h3>账户余额趋势</h3><p>统一折算为 AUD · 最多比较 5 个账户</p></div><div className="account-picker"><button className="soft-btn" onClick={()=>setPicker(!picker)}>选择账户（{selected.length}/5）</button>{picker&&<div className="account-picker-menu">{accounts.map(account=><label key={account.id}><input type="checkbox" checked={selected.includes(account.id)} disabled={!selected.includes(account.id)&&selected.length>=5} onChange={()=>toggle(account.id)}/><span>{account.name}<small>{account.category} · {account.currency}</small></span></label>)}</div>}</div></div><div className="chart-legend">{chosen.map((account,index)=><span key={account.id}><i style={{background:palette[index]}}/>{account.name}</span>)}</div>{hover&&<div className="analytics-tooltip"><b>{hover.month}</b>{hover.values.map(value=><span key={value.name}>{value.name} ${money(value.value)}</span>)}</div>}{chosen.length?<svg viewBox={`0 0 ${w} ${h}`} aria-label="账户余额趋势图"><line className="analytics-grid" x1={left} x2={w-right} y1={chart.y(0)} y2={chart.y(0)}/><text className="axis-value" x={left-8} y={top+4} textAnchor="end">${money(chart.hi)}</text><text className="axis-value" x={left-8} y={h-bottom+4} textAnchor="end">${money(chart.lo)}</text>{chosen.map((account,index)=>{const pointMap=new Map(account.points.map(point=>[point.month,point.value]));const path=monthList.map((month,monthIndex)=>pointMap.has(month)?`${monthIndex&&monthList.slice(0,monthIndex).some(value=>pointMap.has(value))?"L":"M"}${x(monthIndex)},${chart.y(pointMap.get(month)!)} `:"").join("");return <path key={account.id} className="analytics-line" stroke={palette[index]} d={path}/>;})}{monthList.map((month,index)=>{const monthValues=chosen.map(account=>({name:account.name,value:account.points.find(point=>point.month===month)?.value})).filter((value):value is {name:string;value:number}=>value.value!==undefined);return <g key={month} className="clickable-month" {...monthAction(month,onSelectMonth)} onMouseEnter={()=>setHover({month,values:monthValues})} onMouseLeave={()=>setHover(null)}><rect x={x(index)-Math.max(8,(w-left-right)/Math.max(1,monthList.length-1)/2)} y={top} width={Math.max(16,(w-left-right)/Math.max(1,monthList.length-1))} height={h-top-bottom} fill="transparent"/><text x={x(index)} y={h-8} textAnchor="middle">{month.slice(2)}</text>{chosen.map((account,seriesIndex)=>{const value=account.points.find(point=>point.month===month)?.value;return value===undefined?null:<circle key={account.id} cx={x(index)} cy={chart.y(value)} r="4" fill={palette[seriesIndex]}/>;})}</g>;})}</svg>:<div className="analytics-empty">请选择至少一个账户</div>}</section>;
}

export function AnalysisEnhancements({onSelectMonth}:{onSelectMonth:(month:string)=>void}){
  const[data,setData]=useState<Analytics|null>(null),[period,setPeriod]=useState(12),[startMonth,setStartMonth]=useState(""),[endMonth,setEndMonth]=useState("");
  useEffect(()=>{fetch("/api/analytics").then(response=>response.ok?response.json():null).then(result=>{setData(result);if(result?.months?.length){setStartMonth(result.months[Math.max(0,result.months.length-12)].month);setEndMonth(result.months.at(-1).month);}});},[]);
  const months=useMemo(()=>data?data.months.filter(point=>(!startMonth||point.month>=startMonth)&&(!endMonth||point.month<=endMonth)):[],[data,startMonth,endMonth]);
  if(!data)return <div className="analytics-loading">正在生成历史分析…</div>;
  const setQuickRange=(value:number)=>{setPeriod(value);const end=data.months.at(-1)?.month||"";const start=value===0?data.months[0]?.month||"":data.months[Math.max(0,data.months.length-value)]?.month||"";setStartMonth(start);setEndMonth(end);};
  const first=data.months[0]?.month,last=data.months.at(-1)?.month;
  return <div className="analytics-suite"><div className="analytics-toolbar"><div><h2>历史趋势分析</h2><p>所有金额统一折算为 AUD</p></div><div className="analytics-range-controls"><RangeButtons value={period} onChange={setQuickRange}/><div className="custom-date-range"><label>开始<input type="month" min={first} max={endMonth||last} value={startMonth} onChange={event=>{setPeriod(-1);setStartMonth(event.target.value);}}/></label><i>至</i><label>结束<input type="month" min={startMonth||first} max={last} value={endMonth} onChange={event=>{setPeriod(-1);setEndMonth(event.target.value);}}/></label></div></div></div>{months.length?<><TotalsChart points={months} onSelectMonth={onSelectMonth}/><CategoryChart points={months} onSelectMonth={onSelectMonth}/><AccountChart accounts={data.accounts} months={months} onSelectMonth={onSelectMonth}/></>:<div className="analytics-empty">所选日期范围内没有记录，请重新选择。</div>}</div>;
}
